name: AppWright Test

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Clean up previous Docker containers
        run: |
          docker compose down --volumes --remove-orphans || true

      - name: Start backend and agents
        run: |
          docker compose up -d --build --scale agent=3
          echo "Waiting for job-server to become healthy..."
          for i in {1..15}; do
            if curl -s http://localhost:8000/healthz | grep -q "ok"; then
              echo "job-server is up"
              break
            fi
            sleep 3
          done

      - name: Install qgjob CLI
        run: pip install qgjob

      - name: Submit test job
        id: submit
        run: |
          echo "Submitting test job..."
          job_output=$(qgjob submit \
            --org-id=qualgent \
            --app-version-id=ci-${{ github.run_id }} \
            --test=tests/onboarding.spec.ts \
            --target=emulator \
            --priority=1
          )

          echo "$job_output"
          job_id=$(echo "$job_output" | grep -oP '"job_id":\s*"\K[^"]+')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT
          echo "JOB_ID=$job_id" >> $GITHUB_ENV

      - name: Poll test status
        run: |
          echo "Polling status for job: $JOB_ID"
          qgjob status --job-id=$JOB_ID --poll

      - name: Cleanup containers
        if: always()
        run: |
          echo "Cleaning up containers..."
          docker compose down --volumes --remove-orphans
